### ISSUE TITLE
Crash on Minecraft 1.12.2 startup

### ISSUE THREAD

**Issue by Burgersim** [Landmaster/PlusTiC#234]
Hi there, I don't know waht the problem is right now, because I could've sworn my pack did start just fine a few minutes ago with PlusTic and my other mods, but now on startup I get this crash report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 11/21/18 7:31 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PlusTiC (plustic)
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:49)
	at landmaster.plustic.modules.ModuleBase.lambda$init2$1(ModuleBase.java:164)
	at java.util.Optional.ifPresent(Unknown Source)
	at landmaster.plustic.modules.ModuleBase.init2(ModuleBase.java:162)
	at java.lang.Iterable.forEach(Unknown Source)
	at landmaster.plustic.PlusTiC.init(PlusTiC.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 844072192 bytes (804 MB) / 1859649536 bytes (1773 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx3072m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 53 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version           | Source                                        | Signature                                |
	|:----- |:-------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHI  | minecraft            | 1.12.2            | minecraft.jar                                 | None                                     |
	| UCHI  | mcp                  | 9.42              | minecraft.jar                                 | None                                     |
	| UCHI  | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | forge                | 14.23.5.2768      | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHI  | foamfixcore          | 7.7.4             | minecraft.jar                                 | None                                     |
	| UCHI  | mantle               | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| UCHI  | jei                  | 4.13.1.222        | jei_1.12.2-4.13.1.222.jar                     | None                                     |
	| UCHI  | tconstruct           | 1.12.2-2.11.0.106 | TConstruct-1.12.2-2.11.0.106.jar              | None                                     |
	| UCHI  | conarm               | 1.2.0.1           | conarm-1.12.2-1.2.0.1.jar                     | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHI  | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHI  | biomesoplenty        | 7.0.1.2399        | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
	| UCHI  | thaumcraft           | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| UCHEE | plustic              | 6.5.4.1           | plustic-6.5.4.1.jar                           | None                                     |
	| UCH   | taiga                | 1.12.2-1.3.3      | taiga-1.12.2-1.3.4.jar                        | None                                     |
	| UCH   | armoryexpansion      | 0.2.0             | armoryexpansion-0.2.0.jar                     | None                                     |
	| UCH   | quark                | r1.5-130          | Quark-r1.5-130.jar                            | None                                     |
	| UCH   | autoreglib           | 1.3-20            | AutoRegLib-1.3-20.jar                         | None                                     |
	| UCH   | bullseye             | 3.0.6             | Bullseye-1.12.2-3.0.6.jar                     | None                                     |
	| UCH   | ceramics             | 1.12-1.3.6        | Ceramics-1.12-1.3.6.jar                       | None                                     |
	| UCH   | chameleon            | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCH   | cursesilence         | 1.1               | cursesilence-1.1.jar                          | None                                     |
	| UCH   | dummycore            | 2.4.112.5.        | DummyCoreUnofficial-2.4.112.5.jar             | None                                     |
	| UCH   | dynamictrees         | 1.12.2-0.8.2      | DynamicTrees-1.12.2-0.8.2.jar                 | None                                     |
	| UCH   | dynamictreesbop      | 1.12.2-1.3.2      | DynamicTreesBOP-1.12.2-1.3.2.jar              | None                                     |
	| UCH   | rustic               | 1.0.12            | rustic-1.0.12.jar                             | None                                     |
	| UCH   | dynamictreestc       | 1.12.2-1.1.2      | DynamicTreesTC-1.12.2-1.1.2.jar               | None                                     |
	| UCH   | earthworks           | 1.3.4.3           | Earthworks-1.12-1.3.6.jar                     | None                                     |
	| UCH   | immersiveengineering | 0.12-86           | ImmersiveEngineering-0.12-86.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCH   | engineersdoors       | 0.8.0             | engineers_doors-1.12.2-0.8.0.jar              | None                                     |
	| UCH   | extraalchemy         | 0.3.8.6.1-release | extraalchemy-0.3.8.6.1-release.jar            | None                                     |
	| UCH   | familiarfauna        | 1.0.10            | FamiliarFauna-1.12.2-1.0.10.jar               | None                                     |
	| UCH   | fistsofflesh         | 1.3.1             | FistsOfFlesh-1.3.1.jar                        | None                                     |
	| UCH   | foamfix              | 0.10.3-1.12.2     | foamfix-0.10.3-1.12.2.jar                     | None                                     |
	| UCH   | gravestone           | 1.10.1            | gravestone-1.10.1.jar                         | None                                     |
	| UCH   | immersivepetroleum   | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar           | None                                     |
	| UCH   | immersivetech        | 1.3.10            | immersivetech-1.12-1.3.10.jar                 | None                                     |
	| UCH   | journeymap           | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCH   | metalchests          | v3.9.0.g9b0c79e   | MetalChests-v3.9.0.g9b0c79e.jar               | None                                     |
	| UCH   | norecipebook         | 1.2.1             | noRecipeBook_v1.2.2formc1.12.2.jar            | None                                     |
	| UCH   | placebo              | 1.5.0             | Placebo-1.12.2-1.5.0.jar                      | None                                     |
	| UCH   | quarkoddities        | 1                 | QuarkOddities-1.12.2.jar                      | None                                     |
	| UCH   | rusticthaumaturgy    | 1.0               | Rustic+Thaumaturgy-2.7.jar                    | None                                     |
	| UCH   | spectrite            | 1.6.7             | spectrite-1.6.7.jar                           | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
	| UCH   | storagedrawers       | 1.12-5.3.5        | StorageDrawers-1.12.2-5.3.7.jar               | None                                     |
	| UCH   | storagedrawersextra  | @VERSION@         | StorageDrawersExtras-1.12-3.1.0.jar           | None                                     |
	| UCH   | tc6aspects4jei       | 0.0.2a            | tc6aspects4jei-0.0.2a.jar                     | None                                     |
	| UCH   | thaumicbases         | 3.2.270.4r        | thaumicbases-3.2.270.4r.jar                   | None                                     |
	| UCH   | tcinventoryscan      | 2.0.10            | ThaumicInventoryScanning_1.12.2-2.0.10.jar    | None                                     |
	| UCH   | thaumicjei           | 1.2.1             | ThaumicJEI-1.12.2-1.5.5-23.jar                | None                                     |
	| UCH   | tinkersjei           | 1.0               | tinkersjei-1.0.jar                            | None                                     |
	| UCH   | toastcontrol         | 1.7.1             | Toast+Control-1.12.2-1.7.1.jar                | None                                     |
	| UCH   | foundry              | 1.4.5             | ZenFoundry-1.4.5.jar                          | None                                     |
	| UCH   | totemexpansion       | 1.2.2             | totemexpansion-1.2.2-1.12.2.jar               | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
  DummyCore.ASM.DCASMManager
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	[DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.34
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```
Can anybody help me? I can provide a List of my other used mods, if that would be neccessary.

P.S.: Tried deactivating PlusTiC, now I seem to get the same error but from TAIGA, but I can't figure out what exactly is causing the problem...

**Comment by sTiKyt** [comment]
@Burgersim try to run without FoamFix

**Comment by Landmaster** [comment]
Closing as unreproducable
