### ISSUE TITLE
Crash with new 5.0.1.2 version

### ISSUE THREAD

**Issue by Xottab-DUTY** [Landmaster/PlusTiC#50]
_Server on Minecraft 1.11.2 and Forge 13.20.0.2282_

I picked new backed version and got crash. I'm cutted things from crashlog and you can see only what is necessary:
```
Description: Exception in server tick loop
Caused by: java.lang.ClassNotFoundException: com.brandon3055.draconicevolution.items.ItemCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 32 more
Caused by: java.lang.NullPointerException
```
It's seems it wont start without Draconic Evolution

**Comment by Xottab-DUTY** [comment]
Thanks for the hotfix! 👍
