### ISSUE TITLE
1.12 - plustic-6.0.0.3.jar - Crash with newest TC-Dev-Build 

### ISSUE THREAD

**Issue by cyberpunkbln** [Landmaster/PlusTiC#78]
Hello,

so the official download version in curseforge has many bugfix not included. And with the newest compiled version PlusTic crashes. I have checked this with the latest DEV-Build from PlusTic,too.

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-69.jar)
  HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 7/26/17 7:14 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from PlusTiC (plustic)
Caused by: java.lang.NoSuchMethodError: slimeknights.tconstruct.library.MaterialIntegration.integrateRecipes()V
	at landmaster.plustic.PlusTiC.lambda$integrate$4(PlusTiC.java:158)
	at java.util.Map.forEach(Unknown Source)
	at landmaster.plustic.PlusTiC.integrate(PlusTiC.java:157)
	at landmaster.plustic.PlusTiC.init(PlusTiC.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:614)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:781)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1478616304 bytes (1410 MB) / 3741650944 bytes (3568 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn128M -Xms128M -Xmx8G -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2424 Optifine OptiFine_1.12_HD_U_C5_pre 97 mods loaded, 97 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2424.jar) 
	UCHI	forge{14.21.1.2424} [Minecraft Forge] (forge-1.12-14.21.1.2424.jar) 
	UCHI	backpacks16840{3.2.1} [Backpacks!] (zz-backpacks 1.12 - 3.2.1.jar) 
	UCHI	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHI	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCHI	crafttweaker{4.0.1} [CraftTweaker2] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHI	mtlib{@VERSION@} [MTLib] (MTLib-3.0.0.jar) 
	UCHI	modtweaker{4.0.0} [Mod Tweaker] (modtweaker-4.0.0.jar) 
	UCHI	jei{4.7.2.77} [Just Enough Items] (jei_1.12-4.7.2.77.jar) 
	UCHI	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCHI	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCHI	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHI	campfire{1.1} [Simple Camp Fire] (campfire-1.12-v1.1.jar) 
	UCHI	cavern{1.9.4} [Cavern] (Cavern_1.12-v1.9.4.jar) 
	UCHI	chameleon{1.12-4.1.3} [Chameleon] (Chameleon-1.12-4.1.3.jar) 
	UCHI	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCHI	chickenchunks{2.4.0.70} [ChickenChunks] (ChickenChunks-1.12-2.4.0.70-universal.jar) 
	UCHI	chisel{MC1.12-0.0.13.12} [Chisel] (Chisel-MC1.12-0.0.13.12.jar) 
	UCHI	clayworldgen{1.1.0-1.12} [Clay WorldGen] (ClayWorldGen-1.1.0-1.12.0.jar) 
	UCHI	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCHI	cofhcore{4.3.3} [CoFH Core] (CoFHCore-1.12-4.3.3.11-universal.jar) 
	UCHI	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCHI	ctgui{1.0.0} [CT-GUI] (CraftTweaker2-1.12-4.0.1.jar) 
	UCHI	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCHI	dailies{1.12-6} [Bailey's Dailies] (dailies-1.12-6.jar) 
	UCHI	movingworld{1.12-4.340} [Moving World] (movingworld-1.12-4.340-full.jar) 
	UCHI	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-4.334-full.jar) 
	UCHI	dsurround{3.4.6.0} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCHI	presets{3.4.6.0} [Presets!] (DynamicSurroundings-1.12-3.4.6.0.jar) 
	UCHI	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHI	enderstorage{1.0} [EnderStorage] (EnderStorage-1.12-2.4.0.119-universal.jar) 
	UCHI	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UCHI	endertanks{1.6.0.2} [EnderTanks] (endertanks-1.12.0-1.6.0.2.jar) 
	UCHI	externaltweaker{0.3} [External Tweaker] (externaltweaker-1.12-0.3.jar) 
	UCHI	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCHI	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCHI	bigreactors{1.12-0.4.5.34} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.34.jar) 
	UCHI	forestry{5.4.3.146} [Forestry] (forestry_1.12-5.4.3.146.jar) 
	UCHI	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHI	ftbl{0.0.0} [FTBLib] (FTBLib-4.0.5.jar) 
	UCHI	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-4.0.3.jar) 
	UCHI	fp{26.1.2} [Futurepack] (Futurepack-1.12-26.1.2.jar) 
	UCHI	fp.api{1.1.0} [Futurepack API] (Futurepack-1.12-26.1.2.jar) 
	UCHI	grapplemod{1.12-v10} [Grappling hook mod] (grapplemod-1.12-v10.jar) 
	UCHI	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCHI	hammercore{1.9.3.6} [Hammer Core] (HammerCore-1.12-1.9.3.6.jar) 
	UCHI	hardcoreore{0.0.5} [Hardcore ORE] (hardcoreore-1.12-0.0.5.jar) 
	UCHI	mantle{1.12-1.3.0.15} [Mantle] (Mantle-1.12-1.3.0.15.jar) 
	UCHI	tconstruct{1.12-2.7.1.9} [Tinkers' Construct] (TConstruct-1.12-2.7.1.9.jar) 
	UCHI	tesla{1.0.60} [TESLA] (Tesla-1.12-1.0.60.jar) 
	UCHI	theoneprobe{1.4.15} [The One Probe] (theoneprobe-1.12-1.4.15.jar) 
	UCHI	immersiveengineering{0.12-69} [Immersive Engineering] (ImmersiveEngineering-0.12-69.jar) 
	UCHI	immersivepetroleum{1.1.0} [Immersive Petroleum] (immersivepetroleum-1.12-1.1.0.jar) 
	UCHI	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHI	teslacorelib{1.12-1.0.5} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.5.jar) 
	UCHI	industrialforegoing{1.11.2-1.1} [Industrial Foregoing] (industrialforegoing-1.12-1.1-23.jar) 
	UCHI	infinitefluids{1.1.1} [InfiniteFluids] (infinitefluids-1.11-1.1.1.jar) 
	UCHI	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCHI	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHI	minecolonies{1.12-0.8.3167} [MineColonies] (minecolonies-universal-1.12-0.8.3167.jar) 
	UCHI	miniheads{1.0.0} [MiniHeads] (miniheads-1.0.3-1.12.jar) 
	UCHI	modnametooltip{1.8.1} [Mod Name Tooltip] (modnametooltip_1.12-1.8.1.jar) 
	UCHI	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCHI	morepaintings{1.11.2-3.2.1.1} [Paintings++] (morepaintings-paintings-1.12-3.2.1.1.jar) 
	UCHI	multibeds{1.4.0.1} [Multi-Beds] (multibeds-1.12.0-1.4.0.1.jar) 
	UCHI	multistorage{1.4.0.1} [Multi-Storage] (multistorage-1.12.0-1.4.0.1.jar) 
	UCHI	mychunkloader{1.12-01} [My Chunk Loader] (MyChunkloader-1.12-01.jar) 
	UCHI	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCHI	thermalfoundation{2.3.3} [Thermal Foundation] (ThermalFoundation-1.12-2.3.3.10-universal.jar) 
	UCHE	plustic{6.0.0.3} [PlusTiC] (plustic-6.0.0.3.jar) 
	UCHI	guilib{1.11 : updated by subaraki} [GUI Library] (PSG Revamed-1.12-1.0.0.0.jar) 
	UCHI	paintingselgui{1.11 v1: updated by Subaraki} [PaintingSelectionGui] (PSG Revamed-1.12-1.0.0.0.jar) 
	UCHI	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCHI	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCHI	react{1.0.1} [React] (React-1.12-1.0.1.jar) 
	UCHI	reborncore{3.2.5.88} [Reborn Core] (RebornCore-1.12-3.2.5.88-universal.jar) 
	UCHI	thermalexpansion{5.3.3} [Thermal Expansion] (ThermalExpansion-1.12-5.3.3.15-universal.jar) 
	UCHI	redstonearsenal{2.3.3} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.3.11-universal.jar) 
	UCHI	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.9.jar) 
	UCHI	refinedstorage{1.5.13} [Refined Storage] (refinedstorage-1.5.13.jar) 
	UCHI	rftools{6.12} [RFTools] (rftools-1.12-6.12.jar) 
	UCHI	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8.jar) 
	UCHI	rftoolsdim{5.04} [RFTools Dimensions] (rftoolsdim-1.12-5.04.jar) 
	UCHI	rustic{0.3.12} [Rustic] (rustic-0.3.12.jar) 
	UCHI	schopcraft{0.2.0} [SchopCraft Universalis] (SchopCraft-0.2.0.jar) 
	UCHI	simplequarry{1.0.7} [Simple Quarry] (SimpleQuarry-1.12-1.0.7.jar) 
	UCHI	simulatednights{1.12-2.0.0} [Simulated Nights] (simulatednights-1.12-2.0.0.jar) 
	UCHI	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCHI	stevescarts{${version}} [Steve's Carts 2] (StevesCarts-1.12-2.4.6.36.jar) 
	UCHI	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCHI	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCHI	thermaldynamics{2.3.3} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.3.10-universal.jar) 
	UCHI	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UCHI	torohealthmod{1.12-11} [ToroHealth Damage Indicators] (torohealth-1.12-11.jar) 
	UCHI	teslacoreregistries{1.12-1.0.5} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.5.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  brad16840.common.asm.ClassTransformer
MovingWorldCoreMod (movingworld-1.12-4.340-full.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-69.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
HammerCoreCore (HammerCore-1.12-1.9.3.6.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 950M/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.2.5.88
		Runtime Debofucsation 1
		RenderEngine: 1
	OptiFine Version: OptiFine_1.12_HD_U_C5_pre
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 950M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by Protheus** [comment]
Version:
Tinkers: TConstruct-1.12-2.7.2.15
Mantle: Mantle-1.12-1.3.1.18
Forge; 2426
PlucTic: plustic-6.0.0.3

Pastebin: **https://pastebin.com/CjJa9sCx**

**Comment by cyberpunkbln** [comment]
Great Thx
